// DEMO ONLY. Replace placeholders after creating your GitHub repository/token.
// This architecture exposes the token to browser users, so do NOT use it for a real production site.
const CONFIG={owner:'pro-eg-code',repo:'restaurant-menu',branch:'main',token:'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',password:'0000',menuPath:'menu.json',imageDirectory:'images'};
const loginPanel=document.getElementById('loginPanel'),dashboard=document.getElementById('dashboard'),passwordInput=document.getElementById('password'),loginBtn=document.getElementById('loginBtn'),loginStatus=document.getElementById('loginStatus'),productsEl=document.getElementById('products'),adminStatus=document.getElementById('adminStatus'),editor=document.getElementById('editor'),form=document.getElementById('productForm');let menuData={products:[]},menuSha=null,editingId=null;
loginBtn.addEventListener('click',login);passwordInput.addEventListener('keydown',e=>{if(e.key==='Enter')login()});document.getElementById('addBtn').addEventListener('click',()=>openEditor());document.getElementById('reloadBtn').addEventListener('click',loadMenuFromGitHub);document.getElementById('cancelBtn').addEventListener('click',closeEditor);document.getElementById('cancelBtn2').addEventListener('click',closeEditor);form.addEventListener('submit',saveProduct);
function login(){if(passwordInput.value.trim()!==CONFIG.password){loginStatus.textContent='Incorrect password.';return}loginStatus.textContent='';loginPanel.hidden=true;dashboard.hidden=false;loadMenuFromGitHub()}
async function githubRequest(path,options={}){const r=await fetch(`https://api.github.com${path}`,{...options,headers:{Accept:'application/vnd.github+json',Authorization:`Bearer ${CONFIG.token}`,'X-GitHub-Api-Version':'2026-03-10',...(options.headers||{})}});let b=null;try{b=await r.json()}catch{}if(!r.ok)throw new Error(b?.message||`GitHub API error ${r.status}`);return b}
async function loadMenuFromGitHub(){setAdminStatus('Loading menu from GitHub…');try{const r=await githubRequest(`/repos/${encodeURIComponent(CONFIG.owner)}/${encodeURIComponent(CONFIG.repo)}/contents/${encodeURIComponent(CONFIG.menuPath)}?ref=${encodeURIComponent(CONFIG.branch)}`);menuSha=r.sha;menuData=JSON.parse(decodeBase64(r.content));if(!Array.isArray(menuData.products))menuData.products=[];renderProducts();setAdminStatus(`Loaded ${menuData.products.length} product${menuData.products.length===1?'':'s'}.`)}catch(e){console.error(e);setAdminStatus(`Load failed: ${e.message}`)}}
function renderProducts(){if(!menuData.products.length){productsEl.innerHTML='<div class="panel"><p>No products yet.</p></div>';return}productsEl.innerHTML=menuData.products.map(p=>`<article class="admin-item"><div class="admin-main"><img class="thumb" src="${escapeHtml(p.image||'https://placehold.co/200x150?text=No+Image')}" alt=""><div><h3>${escapeHtml(p.name||'Unnamed')}</h3><div class="admin-meta">${Number(p.price||0).toLocaleString('en-US')} EGP · ${escapeHtml(p.category||'Menu')} · ${p.active===false?'Hidden':'Visible'}</div></div></div><div class="admin-actions"><button class="secondary" data-edit="${escapeHtml(p.id)}">Edit</button><button class="secondary" data-delete="${escapeHtml(p.id)}">Delete</button></div></article>`).join('');productsEl.querySelectorAll('[data-edit]').forEach(b=>b.addEventListener('click',()=>openEditor(b.dataset.edit)));productsEl.querySelectorAll('[data-delete]').forEach(b=>b.addEventListener('click',()=>deleteProduct(b.dataset.delete)))}
function openEditor(id=null){editingId=id;editor.hidden=false;document.getElementById('editorEyebrow').textContent=id?'EDIT PRODUCT':'NEW PRODUCT';document.getElementById('editorTitle').textContent=id?'Edit Product':'Add Product';form.reset();document.getElementById('productId').value=id||'';document.getElementById('active').value='true';if(id){const p=menuData.products.find(x=>x.id===id);if(!p)return;document.getElementById('name').value=p.name||'';document.getElementById('price').value=p.price??'';document.getElementById('category').value=p.category||'';document.getElementById('description').value=p.description||'';document.getElementById('active').value=String(p.active!==false);document.getElementById('imageHint').textContent=p.image?`Current image: ${p.image}`:'Optional.'}else document.getElementById('imageHint').textContent='Optional. Images are committed into GitHub.';window.scrollTo({top:editor.offsetTop-20,behavior:'smooth'})}
function closeEditor(){editor.hidden=true;editingId=null}
async function saveProduct(e){e.preventDefault();const name=document.getElementById('name').value.trim(),price=Number(document.getElementById('price').value),category=document.getElementById('category').value.trim(),description=document.getElementById('description').value.trim(),active=document.getElementById('active').value==='true',file=document.getElementById('image').files[0];if(!name||Number.isNaN(price))return;try{setAdminStatus('Saving…');let p=editingId?{...menuData.products.find(x=>x.id===editingId)}:{id:crypto.randomUUID()};p.name=name;p.price=price;p.category=category;p.description=description;p.active=active;if(file){validateImage(file);const path=`${CONFIG.imageDirectory}/${slugify(name)||p.id}-${p.id}.${fileExtension(file.name)}`;await uploadFileToGitHub(path,await fileToBase64(file),`Add image for ${name}`);p.image=`./${path}`}const i=menuData.products.findIndex(x=>x.id===p.id);if(i>=0)menuData.products[i]=p;else menuData.products.push(p);await updateMenuFile();closeEditor();renderProducts();setAdminStatus('Saved. GitHub Pages may take a little time to publish.')}catch(e){console.error(e);setAdminStatus(`Save failed: ${e.message}`)}}
async function deleteProduct(id){const p=menuData.products.find(x=>x.id===id);if(!p)return;if(!confirm(`Delete "${p.name}"?`))return;try{setAdminStatus('Deleting…');menuData.products=menuData.products.filter(x=>x.id!==id);await updateMenuFile();renderProducts();setAdminStatus('Product deleted.')}catch(e){console.error(e);setAdminStatus(`Delete failed: ${e.message}`);loadMenuFromGitHub()}}
async function updateMenuFile(){const r=await githubRequest(`/repos/${encodeURIComponent(CONFIG.owner)}/${encodeURIComponent(CONFIG.repo)}/contents/${encodeURIComponent(CONFIG.menuPath)}`,{method:'PUT',body:JSON.stringify({message:`${editingId?'Update':'Save'} restaurant menu`,content:encodeBase64(JSON.stringify(menuData,null,2)),sha:menuSha,branch:CONFIG.branch})});menuSha=r.content?.sha||menuSha}
async function uploadFileToGitHub(path,content,message){return githubRequest(`/repos/${encodeURIComponent(CONFIG.owner)}/${encodeURIComponent(CONFIG.repo)}/contents/${path.split('/').map(encodeURIComponent).join('/')}`,{method:'PUT',body:JSON.stringify({message,content,branch:CONFIG.branch})})}
function validateImage(f){if(!['image/jpeg','image/png','image/webp'].includes(f.type))throw new Error('Use JPG, PNG, or WebP.');if(f.size>3*1024*1024)throw new Error('Demo limit: image must be 3 MB or smaller.')}
function fileExtension(n){const e=n.split('.').pop()?.toLowerCase();return e==='jpeg'?'jpg':e}
function slugify(t){return t.toLowerCase().trim().replace(/[^a-z0-9]+/g,'-').replace(/^-+|-+$/g,'').slice(0,50)}
function fileToBase64(f){return new Promise((res,rej)=>{const r=new FileReader();r.onload=()=>res(String(r.result).split(',')[1]);r.onerror=rej;r.readAsDataURL(f)})}
function decodeBase64(v){const binary=atob(v.replace(/\n/g,''));const bytes=Uint8Array.from(binary,c=>c.charCodeAt(0));return new TextDecoder().decode(bytes)}
function encodeBase64(v){const bytes=new TextEncoder().encode(v);let binary='';for(let i=0;i<bytes.length;i+=0x8000)binary+=String.fromCharCode(...bytes.subarray(i,i+0x8000));return btoa(binary)}
function escapeHtml(v){return String(v).replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#039;'}[c]))}function setAdminStatus(m){adminStatus.textContent=m}
